import { VerticalBox , HorizontalBox, Button, ListView } from "std-widgets.slint";
import { BorderlessWindow } from "borderless-window.slint";
import { Theme } from "theme.slint";
import { SlideOver } from "slidover.slint";
import { CircularProgressBar } from "circularprogress.slint";

export component Main inherits BorderlessWindow {
    title: "Tomotroid";
    width: 360px;
    height: 480px;

    callback close-window();
    callback move-window(length, length);

    close => {
        close-window();
    }

    move(offset-x, offset-y) => {
        move-window(offset-x, offset-y);
    }

    menu_toggled => {
        slideover.expanded = self.menu_open;
    }

    VerticalLayout {
        HorizontalLayout {
            padding-top: 60px;
            padding-left: 50px;
            padding-right: 50px;

            alignment: center;
            Rectangle {
                height: 230px;
                width: 230px;
                CircularProgressBar {
                    thickness: 2px;
                    prog-color: Theme.background_lightest;
                    value: 99;
                    width: parent.width * 0.95;
                    height: parent.height * 0.95;
                    x: parent.width * 0.025;
                    y: parent.height * 0.025;
                }
                CircularProgressBar {
                    thickness: 10px;
                    prog-color: Theme.focus_round;
                    value: 75;
                    width: parent.width * 0.95;
                    height: parent.height * 0.95;
                    x: parent.width * 0.025;
                    y: parent.height * 0.025;
                }
                    Timer := Text {
                        font-family: "Roboto Mono";
                        text: "25:00";
                        color: Theme.foreground;
                        font-size: 46px;
                    }
                    task_label := Text {
                        text: "FOCUS";
                        font-family: "Lato";
                        y: parent.height * 0.70;
                        color: Theme.foreground;
                        font-size: 12pt;
                    }
            }
        }

        HorizontalLayout {
            alignment: center;
            padding: 20px;
            Rectangle {
                border-color: Theme.foreground-darkest;
                border-width: 2px;
                border-radius: self.height*0.5;
                height: 50px;
                width: 50px;

                animate background {
                    duration: 200ms;
                    easing: ease-in-out;
                }

                StartBtn_ta := TouchArea {

                }

                Image {
                    source: @image-url("../assets/icons/start.svg");
                    animate colorize {
                        duration: 200ms;
                        easing: ease-in-out;
                    }

                    states [
                        hvr when StartBtn_ta.has-hover : {
                            colorize: Theme.accent;
                        }

                        nthvr when !StartBtn_ta.has-hover : {
                            colorize: Theme.foreground;
                        }
                    ]
                }

                states [
                    hvr when StartBtn_ta.has-hover : {
                        background: Theme.background.brighter(0.2);
                    }
                    nthvr when !StartBtn_ta.has-hover : {
                        background: Theme.background;
                    }
                ]
            }
        }
        HorizontalLayout {
            alignment: space-between;
            padding-top: -10px;
            padding-left: 20px;
            padding-right: 15px;
            padding-bottom: -10px;
            Text {
                font-family: "Lato";
                font-weight: 900;
                text: "1/4";
                font-size: 16px;
                color: Theme.foreground-darker;
                vertical-alignment: center;
            }
            HorizontalBox {
                min-width: 80px;
                Rectangle {
                    y: parent.height/2 - self.height/2;
                    SkipBtn_ta := TouchArea {
                    }
                    Image {
                        source: @image-url("../assets/icons/skip.svg");
                        height: 20px;
                        animate colorize {
                            duration: 250ms;
                            easing: ease-in-out;
                        }

                        states [
                            hvr when SkipBtn_ta.has-hover : {
                                colorize: Theme.accent;
                            }

                            nthvr when !SkipBtn_ta.has-hover : {
                                colorize: Theme.background_lightest;
                            }
                        ]
                    }
                }
                Rectangle {
                    y: parent.height/2 - self.height/2;
                    MuteBtn_ta := TouchArea {
                    }
                    Image {
                        source: @image-url("../assets/icons/mute.svg");
                        height: 20px;
                        animate colorize {
                            duration: 250ms;
                            easing: ease-in-out;
                        }

                        states [
                            hvr when MuteBtn_ta.has-hover : {
                                colorize: Theme.accent;
                            }

                            nthvr when !MuteBtn_ta.has-hover : {
                                colorize: Theme.background_lightest;
                            }
                        ]
                    }

                }
            }
        }

        HorizontalLayout {
            padding-top: 5px;
            padding-left: 15px;
            padding-right: 15px;
            alignment: start;
            Text {
                ResetBtn_ta := TouchArea {}
                font-weight: 900;
                text: "Reset";
                font-size: 14px;

                states [
                    hvr when ResetBtn_ta.has-hover : {
                        color: Theme.accent;
                    }

                    nthvr when !ResetBtn_ta.has-hover : {
                        color: Theme.foreground-darker;
                    }
                ]
            }
        }
    }

    slideover := SlideOver {
        x: 0px;
        y: 30px;
        width: root.width;
        height: parent.height - 68px;
        expanded: false;
    }
}
