


export component CircularProgressBar inherits Path {
    function polarToCartesian(cx: int, cy: int, r: int, degrees: float) -> {x: float, y: float} {
        return {
            x: cx + (r * Math.cos((degrees * 1deg) - 90deg)),
            y: cy + (r * Math.sin((degrees * 1deg) - 90deg)),
        };
    }

    in-out property <int> value: 99;

    in property<int> minimum: 0;
    in property<int> maximum: 100;
    in property<color> prog_color: green;
    in property<color> track_color: gray;
    in property<bool> clockwise: false;
    in property<length> thickness: 10px;

    property<float> perc_deg: maximum == 0 ? 0.0 : ((value > maximum ? maximum : value) / maximum) * 360.0;
    property<{x: float, y: float}> start: polarToCartesian(self.width/2px, self.height/2px, (self.width - (thickness/2))/2px, perc_deg);
    property<{x: float, y: float}> stop: polarToCartesian(self.width/2px, self.height/2px, (self.width - (thickness/2))/2px, 0);
    property<bool> large_arc: perc_deg <= 180 ? false : true;

    stroke: prog_color;
    stroke-width: thickness;
    //no linecap it seems...hmmm In pomodor it uses a rounded line cap...but it looks like these paths can only have a squared off one? Need to dig a bit more
    viewbox-height: self.height/1px;
    viewbox-width: self.width/1px;

    MoveTo {
        x: start.x;
        y: start.y;
    }
    ArcTo {
        radius-x: parent.width/2px;
        radius-y: parent.height /2px;
        large-arc: large_arc;
        sweep: clockwise;
        x: stop.x;
        y: stop.y;
    }
}