export global HLClick {
    pure callback hl_clicked(string);
}

export component HyperLink inherits Text {
    in property<string> link_text;
    in property<string> url;
    in property<color> link-color;
    in property<color> hvr-color;

    text: link_text;

    hl_ta := TouchArea {
        clicked => { HLClick.hl_clicked(url)}
    }

    states [
        has_hvr when hl_ta.has-hover: {
            color: hvr-color;
        }
        has_hvr when !hl_ta.has-hover: {
            color: link-color;
        }
    ]

}