//default color theme is "Pomotroid" from Pomotroid software I'm mimicking.
export global Theme {
    in-out property <brush> long_round: #0bbddb;
    in-out property <brush> short_round: #05ec8c;
    in-out property <brush> focus_round: #ff4e4d;
    in-out property <brush> background: #2f384b;
    in-out property <brush> background_light: #3d4457;
    in-out property <brush> background_lightest: #9ca5b5;
    in-out property <brush> foreground: #f6f2eb;
    in-out property <brush> foreground-darker: #c0c9da;
    in-out property <brush> foreground-darkest: #dbe1ef;
    in-out property <brush> accent: #05ec8c;
    in-out property<length> letter-spacing: 3px;
    in-out property<image> logo: @image-url("../assets/logo.svg");
}

//@rust-attr(derive(serde::Deserialize))
export struct JsonTheme {
    name: string,
    long_round: brush,
    short_round: brush,
    focus_round: brush,
    background: brush,
    background_light: brush,
    background_lightest: brush,
    foreground: brush,
    foreground_darker: brush,
    foreground_darkest: brush,
    accent: brush,
}